baseurl = "https://www.enterpriseready.io"
languageCode = "en-us"
title = "EnterpriseReady"
theme = "hugo-theme-enterpriseready"

[taxonomies]
  feature = "features"

[params]
  description = "EnvironmentReady"
  ogimage = "/images/ephemeral-logo.png"
  copyright = "Shipyard Build, Inc."
  edit_link = "https://github.com/enterpriseready/enterpriseready/edit/master/docs/"
  search = true
  contributor ="Shipyard"
  contributorurl = "https://www.shipyard.build"
  matomo_host = "data-2.replicated.com"
  matomo_site = "4"
  image = "/images/ephemeral-logo.png"
